name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build_Linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Enable Corepack before setting up Node
        run: corepack enable

      - name: Setup node env
        uses: actions/setup-node@v4
        with:
          node-version: lts/Iron
          check-latest: true

      - name: Install dependencies
        run: yarn --frozen-lockfile --silent

      - name: Run prepare
        run: yarn prepare

      - name: Run linter
        run: yarn lint

      - name: Run build
        run: yarn build

      - uses: actions/upload-artifact@v4
        with:
          name: build-linux
          path: .output

  Build_Windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Enable Corepack before setting up Node
        run: corepack enable

      - name: Setup node env
        uses: actions/setup-node@v4
        with:
          node-version: lts/Iron
          check-latest: true

      - name: Enable Corepack before setting up Node
        run: corepack enable

      - name: Install dependencies
        run: yarn --frozen-lockfile --silent

      - name: Run prepare
        run: yarn prepare

      - name: Run linter
        run: yarn lint

      - name: Run build
        run: yarn build

      - uses: actions/upload-artifact@v4
        with:
          name: build-windows
          path: .output
